// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: execution/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgBatchIngest defines the message for batch data submission (Blob-like)
type MsgBatchIngest struct {
	// sender is the address of the sender
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	// batch_id is the unique identifier for this batch (client-generated)
	BatchId string `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty" yaml:"batch_id"`
	// source_data is the base64-encoded raw data (not stored in state)
	SourceData string `protobuf:"bytes,3,opt,name=source_data,json=sourceData,proto3" json:"source_data,omitempty" yaml:"source_data"`
}

func (m *MsgBatchIngest) Reset()         { *m = MsgBatchIngest{} }
func (m *MsgBatchIngest) String() string { return proto.CompactTextString(m) }
func (*MsgBatchIngest) ProtoMessage()    {}
func (*MsgBatchIngest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef35aaae1c0a75d, []int{0}
}
func (m *MsgBatchIngest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBatchIngest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBatchIngest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBatchIngest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBatchIngest.Merge(m, src)
}
func (m *MsgBatchIngest) XXX_Size() int {
	return m.Size()
}
func (m *MsgBatchIngest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBatchIngest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBatchIngest proto.InternalMessageInfo

// MsgBatchIngestResponse defines the response for batch data submission
type MsgBatchIngestResponse struct {
	// batch_id is the batch identifier
	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty" yaml:"batch_id"`
	// tx_hash is the SHA256 hash of the transaction (hex-encoded)
	TxHash string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty" yaml:"tx_hash"`
}

func (m *MsgBatchIngestResponse) Reset()         { *m = MsgBatchIngestResponse{} }
func (m *MsgBatchIngestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBatchIngestResponse) ProtoMessage()    {}
func (*MsgBatchIngestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef35aaae1c0a75d, []int{1}
}
func (m *MsgBatchIngestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBatchIngestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBatchIngestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBatchIngestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBatchIngestResponse.Merge(m, src)
}
func (m *MsgBatchIngestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBatchIngestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBatchIngestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBatchIngestResponse proto.InternalMessageInfo

func (m *MsgBatchIngestResponse) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *MsgBatchIngestResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgBatchIngest)(nil), "seiprotocol.seichain.execution.MsgBatchIngest")
	proto.RegisterType((*MsgBatchIngestResponse)(nil), "seiprotocol.seichain.execution.MsgBatchIngestResponse")
}

func init() { proto.RegisterFile("execution/tx.proto", fileDescriptor_6ef35aaae1c0a75d) }

var fileDescriptor_6ef35aaae1c0a75d = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xb1, 0x4a, 0xc3, 0x40,
	0x1c, 0xc6, 0x73, 0x16, 0xda, 0x7a, 0xc5, 0x8a, 0xa7, 0x94, 0xd2, 0xe1, 0x22, 0x37, 0x29, 0xe2,
	0x05, 0x2c, 0x28, 0x74, 0x2c, 0x0e, 0x76, 0xe8, 0x92, 0xd1, 0xa5, 0x5c, 0x93, 0x23, 0x39, 0x68,
	0x73, 0xa5, 0x77, 0x81, 0x14, 0x7c, 0x00, 0x47, 0x1f, 0xa1, 0x4f, 0xe0, 0x73, 0x38, 0x76, 0x74,
	0x0a, 0xd2, 0x2e, 0xce, 0x79, 0x02, 0xe9, 0x25, 0xd5, 0x66, 0x11, 0xdd, 0xfe, 0xff, 0x7c, 0xbf,
	0xef, 0xe3, 0xcb, 0x9f, 0x83, 0x88, 0x27, 0xdc, 0x8b, 0xb5, 0x90, 0x91, 0xa3, 0x13, 0x3a, 0x9b,
	0x4b, 0x2d, 0x11, 0x56, 0x5c, 0x98, 0xc9, 0x93, 0x13, 0xaa, 0xb8, 0xf0, 0x42, 0x26, 0x22, 0xfa,
	0x0d, 0x76, 0xce, 0x02, 0x19, 0x48, 0x03, 0x38, 0xdb, 0x29, 0x77, 0x91, 0x57, 0x00, 0x9b, 0x43,
	0x15, 0xf4, 0x99, 0xf6, 0xc2, 0x41, 0x14, 0x70, 0xa5, 0xd1, 0x25, 0xac, 0x2a, 0x1e, 0xf9, 0x7c,
	0xde, 0x06, 0xe7, 0xe0, 0xe2, 0xb0, 0x7f, 0x92, 0xa5, 0xf6, 0xd1, 0x82, 0x4d, 0x27, 0x3d, 0x92,
	0x7f, 0x27, 0x6e, 0x01, 0x20, 0x0a, 0xeb, 0xe3, 0xad, 0x73, 0x24, 0xfc, 0xf6, 0x81, 0x81, 0x4f,
	0xb3, 0xd4, 0x3e, 0xce, 0xe1, 0x9d, 0x42, 0xdc, 0x9a, 0x19, 0x07, 0x3e, 0xba, 0x83, 0x0d, 0x25,
	0xe3, 0xb9, 0xc7, 0x47, 0x3e, 0xd3, 0xac, 0x5d, 0x31, 0x96, 0x56, 0x96, 0xda, 0xa8, 0xc8, 0xff,
	0x11, 0x89, 0x0b, 0xf3, 0xed, 0x9e, 0x69, 0xd6, 0xab, 0x3f, 0x2f, 0x6d, 0xeb, 0x73, 0x69, 0x5b,
	0x24, 0x86, 0xad, 0x72, 0x5f, 0x97, 0xab, 0x99, 0x8c, 0x14, 0x2f, 0x95, 0x01, 0x7f, 0x28, 0x73,
	0x05, 0x6b, 0x3a, 0x19, 0x85, 0x4c, 0x85, 0x45, 0x77, 0x94, 0xa5, 0x76, 0x33, 0xc7, 0x0b, 0x81,
	0xb8, 0x55, 0x9d, 0x3c, 0x30, 0x15, 0xde, 0x3c, 0xc1, 0xca, 0x50, 0x05, 0x28, 0x86, 0x8d, 0xfd,
	0x53, 0x51, 0xfa, 0xfb, 0xd1, 0x69, 0xb9, 0x6a, 0xe7, 0xf6, 0x7f, 0xfc, 0xee, 0xd7, 0xfa, 0xc3,
	0xb7, 0x35, 0x06, 0xab, 0x35, 0x06, 0x1f, 0x6b, 0x0c, 0x5e, 0x36, 0xd8, 0x5a, 0x6d, 0xb0, 0xf5,
	0xbe, 0xc1, 0xd6, 0x63, 0x37, 0x10, 0x3a, 0x8c, 0xc7, 0xd4, 0x93, 0x53, 0x47, 0x71, 0x71, 0xbd,
	0x0b, 0x37, 0x8b, 0x49, 0x77, 0x12, 0x67, 0xef, 0xb5, 0x2c, 0x66, 0x5c, 0x8d, 0xab, 0x86, 0xea,
	0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x16, 0x5e, 0xe0, 0x00, 0x47, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// BatchIngest batch ingests order data
	BatchIngest(ctx context.Context, in *MsgBatchIngest, opts ...grpc.CallOption) (*MsgBatchIngestResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) BatchIngest(ctx context.Context, in *MsgBatchIngest, opts ...grpc.CallOption) (*MsgBatchIngestResponse, error) {
	out := new(MsgBatchIngestResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.execution.Msg/BatchIngest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// BatchIngest batch ingests order data
	BatchIngest(context.Context, *MsgBatchIngest) (*MsgBatchIngestResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) BatchIngest(ctx context.Context, req *MsgBatchIngest) (*MsgBatchIngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIngest not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_BatchIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBatchIngest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BatchIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.execution.Msg/BatchIngest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BatchIngest(ctx, req.(*MsgBatchIngest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.execution.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchIngest",
			Handler:    _Msg_BatchIngest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execution/tx.proto",
}

func (m *MsgBatchIngest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBatchIngest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBatchIngest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SourceData) > 0 {
		i -= len(m.SourceData)
		copy(dAtA[i:], m.SourceData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceData)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBatchIngestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBatchIngestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBatchIngestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBatchIngest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BatchId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBatchIngestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BatchId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBatchIngest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBatchIngest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBatchIngest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBatchIngestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBatchIngestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBatchIngestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
