// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aexburn/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the aexburn module's genesis state.
type GenesisState struct {
	// params defines the module parameters
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// burn_stats contains the cumulative burn statistics
	BurnStats BurnStats `protobuf:"bytes,2,opt,name=burn_stats,json=burnStats,proto3" json:"burn_stats"`
	// inflation_stats contains the cumulative inflation statistics
	InflationStats InflationStats `protobuf:"bytes,3,opt,name=inflation_stats,json=inflationStats,proto3" json:"inflation_stats"`
	// monthly_burn_data contains the 12-month rolling window supply data (burn + mint)
	MonthlyBurnData []MonthlyBurnData `protobuf:"bytes,4,rep,name=monthly_burn_data,json=monthlyBurnData,proto3" json:"monthly_burn_data"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d84f32a34bde1e20, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetBurnStats() BurnStats {
	if m != nil {
		return m.BurnStats
	}
	return BurnStats{}
}

func (m *GenesisState) GetInflationStats() InflationStats {
	if m != nil {
		return m.InflationStats
	}
	return InflationStats{}
}

func (m *GenesisState) GetMonthlyBurnData() []MonthlyBurnData {
	if m != nil {
		return m.MonthlyBurnData
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "seiprotocol.seichain.aexburn.GenesisState")
}

func init() { proto.RegisterFile("aexburn/genesis.proto", fileDescriptor_d84f32a34bde1e20) }

var fileDescriptor_d84f32a34bde1e20 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xdb, 0x6d, 0x0c, 0xfe, 0xd9, 0x1f, 0x87, 0x61, 0x42, 0x29, 0x12, 0x87, 0x08, 0xee,
	0xe0, 0x52, 0x9c, 0xdf, 0xa0, 0x08, 0x22, 0x2a, 0x88, 0xde, 0xf4, 0x50, 0xd2, 0x1a, 0xdb, 0x40,
	0x9b, 0x94, 0x26, 0x85, 0xed, 0x5b, 0xf8, 0xb1, 0x76, 0xdc, 0xd1, 0xd3, 0x90, 0xf6, 0x8b, 0x48,
	0xd3, 0x06, 0xd4, 0x43, 0x2f, 0xe5, 0xed, 0xf3, 0xbe, 0xcf, 0xef, 0x79, 0x20, 0xe0, 0x88, 0xd0,
	0x75, 0x58, 0x16, 0xdc, 0x8b, 0x29, 0xa7, 0x92, 0x49, 0x9c, 0x17, 0x42, 0x09, 0x78, 0x2c, 0x29,
	0xd3, 0x53, 0x24, 0x52, 0x2c, 0x29, 0x8b, 0x12, 0xc2, 0x38, 0xee, 0x6e, 0xdd, 0x59, 0x2c, 0x62,
	0xa1, 0xd7, 0x5e, 0x33, 0xb5, 0x1e, 0x77, 0x66, 0x50, 0x39, 0x29, 0x48, 0xd6, 0x91, 0x5c, 0x68,
	0xd4, 0xe6, 0xd3, 0x6a, 0xa7, 0xfb, 0x01, 0xf8, 0x7f, 0xd3, 0xe6, 0x3d, 0x2b, 0xa2, 0x28, 0xf4,
	0xc1, 0xb8, 0x35, 0x39, 0xf6, 0xdc, 0x5e, 0x4c, 0x56, 0x67, 0xb8, 0x2f, 0x1f, 0x3f, 0xea, 0x5b,
	0x7f, 0xb4, 0xdd, 0x9f, 0x58, 0x4f, 0x9d, 0x13, 0xde, 0x03, 0xd0, 0x2c, 0x03, 0xa9, 0x88, 0x92,
	0xce, 0x40, 0x73, 0xce, 0xfb, 0x39, 0x7e, 0x59, 0xf0, 0xa6, 0x80, 0x41, 0xfd, 0x0b, 0x8d, 0x00,
	0x5f, 0xc1, 0x94, 0xf1, 0xf7, 0x94, 0x28, 0x26, 0x0c, 0x72, 0xa8, 0x91, 0x17, 0xfd, 0xc8, 0x5b,
	0x63, 0xfa, 0xc9, 0x3d, 0x60, 0xbf, 0x54, 0x18, 0x80, 0xc3, 0x4c, 0x70, 0x95, 0xa4, 0x9b, 0x40,
	0x57, 0x7e, 0x23, 0x8a, 0x38, 0xa3, 0xf9, 0x70, 0x31, 0x59, 0x2d, 0xfb, 0xf1, 0x0f, 0xad, 0xad,
	0x29, 0x7e, 0x4d, 0x14, 0xe9, 0xf8, 0xd3, 0xec, 0x8f, 0x7c, 0xb7, 0xad, 0x90, 0xbd, 0xab, 0x90,
	0xfd, 0x55, 0x21, 0xfb, 0xa3, 0x46, 0xd6, 0xae, 0x46, 0xd6, 0x67, 0x8d, 0xac, 0x97, 0xcb, 0x98,
	0xa9, 0xa4, 0x0c, 0x71, 0x24, 0x32, 0x4f, 0x52, 0xb6, 0x34, 0x51, 0xfa, 0x47, 0x67, 0x79, 0x6b,
	0xcf, 0x3c, 0x99, 0xda, 0xe4, 0x54, 0x86, 0x63, 0x7d, 0x73, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x4f, 0xa0, 0x0e, 0x48, 0x2b, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MonthlyBurnData) > 0 {
		for iNdEx := len(m.MonthlyBurnData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MonthlyBurnData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.InflationStats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.BurnStats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.BurnStats.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.InflationStats.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MonthlyBurnData) > 0 {
		for _, e := range m.MonthlyBurnData {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthlyBurnData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MonthlyBurnData = append(m.MonthlyBurnData, MonthlyBurnData{})
			if err := m.MonthlyBurnData[len(m.MonthlyBurnData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
