// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aexburn/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the aexburn module.
type Params struct {
	// burn_enabled determines whether fee burning is enabled
	BurnEnabled bool `protobuf:"varint,1,opt,name=burn_enabled,json=burnEnabled,proto3" json:"burn_enabled,omitempty" yaml:"burn_enabled"`
	// min_burn_rate is the minimum burn rate (0.30 = 30%)
	MinBurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=min_burn_rate,json=minBurnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_burn_rate" yaml:"min_burn_rate"`
	// max_burn_rate is the maximum burn rate (0.60 = 60%)
	MaxBurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=max_burn_rate,json=maxBurnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_burn_rate" yaml:"max_burn_rate"`
	// target_burn_rate is the target burn rate when gas usage is normal (0.50 = 50%)
	TargetBurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=target_burn_rate,json=targetBurnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"target_burn_rate" yaml:"target_burn_rate"`
	// low_gas_threshold is the gas usage rate below which burn rate decreases (0.30 = 30%)
	LowGasThreshold github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=low_gas_threshold,json=lowGasThreshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"low_gas_threshold" yaml:"low_gas_threshold"`
	// high_gas_threshold is the gas usage rate above which burn rate increases (0.70 = 70%)
	HighGasThreshold github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=high_gas_threshold,json=highGasThreshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"high_gas_threshold" yaml:"high_gas_threshold"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3cdf38b257635a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBurnEnabled() bool {
	if m != nil {
		return m.BurnEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "seiprotocol.seichain.aexburn.Params")
}

func init() { proto.RegisterFile("aexburn/params.proto", fileDescriptor_eb3cdf38b257635a) }

var fileDescriptor_eb3cdf38b257635a = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0xd3, 0xcd, 0x4e, 0xab, 0x40,
	0x14, 0x07, 0x70, 0xb8, 0xb7, 0x6d, 0xee, 0xa5, 0x7e, 0x54, 0x6c, 0x52, 0x34, 0x06, 0x1a, 0x16,
	0xa6, 0x9b, 0x42, 0x8c, 0xbb, 0x2e, 0x89, 0x1f, 0xd1, 0x6e, 0x0c, 0x71, 0xe5, 0x86, 0x0c, 0x74,
	0x02, 0xa3, 0xc0, 0x34, 0xcc, 0xd4, 0xd2, 0x57, 0x70, 0xe5, 0xd2, 0xa5, 0x8f, 0xd3, 0x65, 0x97,
	0xc6, 0x05, 0x31, 0xed, 0x1b, 0xf4, 0x09, 0x0c, 0x33, 0x6d, 0x83, 0xed, 0xaa, 0x71, 0xc5, 0x9c,
	0x33, 0x87, 0xff, 0x8f, 0xc5, 0x41, 0xaa, 0x03, 0x98, 0xba, 0x83, 0x24, 0x36, 0xfb, 0x20, 0x01,
	0x11, 0x31, 0xfa, 0x09, 0xa6, 0x58, 0x3e, 0x21, 0x10, 0xb1, 0x93, 0x87, 0x43, 0x83, 0x40, 0xe4,
	0x05, 0x00, 0xc5, 0xc6, 0x62, 0xf4, 0xb8, 0xee, 0x63, 0x1f, 0xb3, 0x6b, 0x33, 0x3f, 0xf1, 0x77,
	0xf4, 0x97, 0xb2, 0x54, 0xb9, 0x63, 0x21, 0x72, 0x47, 0xda, 0xc9, 0x07, 0x1d, 0x18, 0x03, 0x37,
	0x84, 0x3d, 0x45, 0x6c, 0x8a, 0xad, 0x7f, 0x56, 0x63, 0x9e, 0x69, 0x87, 0x23, 0x10, 0x85, 0x1d,
	0xbd, 0x78, 0xab, 0xdb, 0xd5, 0xbc, 0xbc, 0xe4, 0x95, 0xfc, 0x28, 0xed, 0x46, 0x28, 0x76, 0xd8,
	0x44, 0x02, 0x28, 0x54, 0xfe, 0x34, 0xc5, 0xd6, 0x7f, 0xeb, 0x6a, 0x9c, 0x69, 0xc2, 0x67, 0xa6,
	0x9d, 0xfa, 0x88, 0x06, 0x03, 0xd7, 0xf0, 0x70, 0x64, 0x7a, 0x98, 0x44, 0x98, 0x2c, 0x1e, 0x6d,
	0xd2, 0x7b, 0x32, 0xe9, 0xa8, 0x0f, 0x89, 0x71, 0x01, 0xbd, 0x79, 0xa6, 0xd5, 0x39, 0xf5, 0x23,
	0x4c, 0xb7, 0xab, 0x11, 0x8a, 0xad, 0x41, 0x12, 0xdb, 0x80, 0x42, 0x66, 0x81, 0xb4, 0x60, 0xfd,
	0xfd, 0xa5, 0x55, 0x0c, 0xcb, 0x2d, 0x90, 0xae, 0x2c, 0x22, 0xd5, 0x28, 0x48, 0x7c, 0x48, 0x0b,
	0x5c, 0x89, 0x71, 0x37, 0x5b, 0x73, 0x0d, 0xce, 0xad, 0xe7, 0xe9, 0xf6, 0x1e, 0x6f, 0xad, 0xd0,
	0x67, 0xe9, 0x20, 0xc4, 0x43, 0xc7, 0x07, 0xc4, 0xa1, 0x41, 0x02, 0x49, 0x80, 0xc3, 0x9e, 0x52,
	0x66, 0xea, 0xed, 0xd6, 0xaa, 0xc2, 0xd5, 0x8d, 0x40, 0xdd, 0xde, 0x0f, 0xf1, 0xf0, 0x1a, 0x90,
	0xfb, 0x65, 0x47, 0x1e, 0x49, 0x72, 0x80, 0xfc, 0x60, 0x0d, 0xae, 0x30, 0xb8, 0xbb, 0x35, 0x7c,
	0xc4, 0xe1, 0xcd, 0x44, 0xdd, 0xae, 0xe5, 0xcd, 0x22, 0xdd, 0x29, 0xbd, 0xbd, 0x6b, 0x82, 0xd5,
	0x1d, 0x4f, 0x55, 0x71, 0x32, 0x55, 0xc5, 0xaf, 0xa9, 0x2a, 0xbe, 0xce, 0x54, 0x61, 0x32, 0x53,
	0x85, 0x8f, 0x99, 0x2a, 0x3c, 0x9c, 0x15, 0x58, 0x02, 0x51, 0x7b, 0xb9, 0xe6, 0xac, 0x60, 0x7b,
	0x6e, 0xa6, 0xe6, 0xf2, 0xa7, 0x60, 0x5f, 0xe1, 0x56, 0xd8, 0xcc, 0xf9, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xbd, 0x6f, 0x0a, 0x56, 0x2c, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.HighGasThreshold.Size()
		i -= size
		if _, err := m.HighGasThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.LowGasThreshold.Size()
		i -= size
		if _, err := m.LowGasThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.TargetBurnRate.Size()
		i -= size
		if _, err := m.TargetBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MaxBurnRate.Size()
		i -= size
		if _, err := m.MaxBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinBurnRate.Size()
		i -= size
		if _, err := m.MinBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.BurnEnabled {
		i--
		if m.BurnEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BurnEnabled {
		n += 2
	}
	l = m.MinBurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxBurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TargetBurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.LowGasThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.HighGasThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BurnEnabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowGasThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LowGasThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighGasThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HighGasThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
