// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aexburn/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the aexburn module.
type Params struct {
	// burn_enabled determines whether fee burning is enabled
	BurnEnabled bool `protobuf:"varint,1,opt,name=burn_enabled,json=burnEnabled,proto3" json:"burn_enabled,omitempty" yaml:"burn_enabled"`
	// min_burn_rate is the minimum burn rate (0.30 = 30%)
	MinBurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=min_burn_rate,json=minBurnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_burn_rate" yaml:"min_burn_rate"`
	// max_burn_rate is the maximum burn rate (0.60 = 60%)
	MaxBurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=max_burn_rate,json=maxBurnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_burn_rate" yaml:"max_burn_rate"`
	// target_burn_rate is the target burn rate when gas usage is normal (0.50 = 50%)
	TargetBurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=target_burn_rate,json=targetBurnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"target_burn_rate" yaml:"target_burn_rate"`
	// low_gas_threshold is the gas usage rate below which burn rate decreases (0.30 = 30%)
	LowGasThreshold github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=low_gas_threshold,json=lowGasThreshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"low_gas_threshold" yaml:"low_gas_threshold"`
	// high_gas_threshold is the gas usage rate above which burn rate increases (0.70 = 70%)
	HighGasThreshold github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=high_gas_threshold,json=highGasThreshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"high_gas_threshold" yaml:"high_gas_threshold"`
	// inflation_enabled determines whether inflation is enabled
	InflationEnabled bool `protobuf:"varint,10,opt,name=inflation_enabled,json=inflationEnabled,proto3" json:"inflation_enabled,omitempty" yaml:"inflation_enabled"`
	// max_annual_inflation_rate is the maximum annual inflation rate (0.03 = 3%)
	MaxAnnualInflationRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,11,opt,name=max_annual_inflation_rate,json=maxAnnualInflationRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_annual_inflation_rate" yaml:"max_annual_inflation_rate"`
	// max_net_supply_rate_per_year is the maximum net supply change rate per 12 months (0.05 = 5%)
	MaxNetSupplyRatePerYear github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,12,opt,name=max_net_supply_rate_per_year,json=maxNetSupplyRatePerYear,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_net_supply_rate_per_year" yaml:"max_net_supply_rate_per_year"`
	// initial_supply is the initial AEX supply for calculating constraints (500M * 10^6 = 500000000000000)
	InitialSupply github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,13,opt,name=initial_supply,json=initialSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"initial_supply" yaml:"initial_supply"`
	// min_gas_usage_for_inflation is the minimum gas usage rate to trigger inflation (0.50 = 50%)
	MinGasUsageForInflation github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,14,opt,name=min_gas_usage_for_inflation,json=minGasUsageForInflation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_gas_usage_for_inflation" yaml:"min_gas_usage_for_inflation"`
	// epochs_per_year is the number of epochs per year for calculating annual limits
	EpochsPerYear uint64 `protobuf:"varint,15,opt,name=epochs_per_year,json=epochsPerYear,proto3" json:"epochs_per_year,omitempty" yaml:"epochs_per_year"`
	// reverse_brake_enabled determines whether reverse brake is enabled
	ReverseBrakeEnabled bool `protobuf:"varint,20,opt,name=reverse_brake_enabled,json=reverseBrakeEnabled,proto3" json:"reverse_brake_enabled,omitempty" yaml:"reverse_brake_enabled"`
	// reverse_brake_trigger_count is the number of consecutive negative net supply periods to trigger brake
	ReverseBrakeTriggerCount uint32 `protobuf:"varint,21,opt,name=reverse_brake_trigger_count,json=reverseBrakeTriggerCount,proto3" json:"reverse_brake_trigger_count,omitempty" yaml:"reverse_brake_trigger_count"`
	// reverse_brake_reduction_rate is the amount to reduce burn rate when brake is triggered (e.g., 0.10 = reduce by 10%)
	ReverseBrakeReductionRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,22,opt,name=reverse_brake_reduction_rate,json=reverseBrakeReductionRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reverse_brake_reduction_rate" yaml:"reverse_brake_reduction_rate"`
	// income_smoother_enabled determines whether validator income smoothing is enabled
	IncomeSmootherEnabled bool `protobuf:"varint,30,opt,name=income_smoother_enabled,json=incomeSmootherEnabled,proto3" json:"income_smoother_enabled,omitempty" yaml:"income_smoother_enabled"`
	// buffer_contribution_rate is the rate to contribute to buffer during high activity (0.10 = 10%)
	BufferContributionRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,31,opt,name=buffer_contribution_rate,json=bufferContributionRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"buffer_contribution_rate" yaml:"buffer_contribution_rate"`
	// buffer_release_rate is the rate to release from buffer during low activity (0.05 = 5%)
	BufferReleaseRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,32,opt,name=buffer_release_rate,json=bufferReleaseRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"buffer_release_rate" yaml:"buffer_release_rate"`
	// high_activity_threshold is the gas usage rate above which income is contributed to buffer (0.70 = 70%)
	HighActivityThreshold github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,33,opt,name=high_activity_threshold,json=highActivityThreshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"high_activity_threshold" yaml:"high_activity_threshold"`
	// low_activity_threshold is the gas usage rate below which buffer releases funds (0.30 = 30%)
	LowActivityThreshold github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,34,opt,name=low_activity_threshold,json=lowActivityThreshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"low_activity_threshold" yaml:"low_activity_threshold"`
	// max_buffer_size is the maximum size of the income buffer (as a fraction of initial supply, 0.01 = 1%)
	MaxBufferSize github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,35,opt,name=max_buffer_size,json=maxBufferSize,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_buffer_size" yaml:"max_buffer_size"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3cdf38b257635a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBurnEnabled() bool {
	if m != nil {
		return m.BurnEnabled
	}
	return false
}

func (m *Params) GetInflationEnabled() bool {
	if m != nil {
		return m.InflationEnabled
	}
	return false
}

func (m *Params) GetEpochsPerYear() uint64 {
	if m != nil {
		return m.EpochsPerYear
	}
	return 0
}

func (m *Params) GetReverseBrakeEnabled() bool {
	if m != nil {
		return m.ReverseBrakeEnabled
	}
	return false
}

func (m *Params) GetReverseBrakeTriggerCount() uint32 {
	if m != nil {
		return m.ReverseBrakeTriggerCount
	}
	return 0
}

func (m *Params) GetIncomeSmootherEnabled() bool {
	if m != nil {
		return m.IncomeSmootherEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "seiprotocol.seichain.aexburn.Params")
}

func init() { proto.RegisterFile("aexburn/params.proto", fileDescriptor_eb3cdf38b257635a) }

var fileDescriptor_eb3cdf38b257635a = []byte{
	// 926 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6f, 0xdb, 0x36,
	0x14, 0xb6, 0xb6, 0x2c, 0xd8, 0x98, 0x3a, 0x3f, 0x1c, 0xff, 0x50, 0x52, 0xcf, 0xf2, 0x58, 0xa0,
	0xc8, 0xa5, 0x36, 0x86, 0xdd, 0x72, 0xab, 0xbb, 0x35, 0xcb, 0x3a, 0x6c, 0x19, 0x93, 0x1e, 0xd6,
	0x8b, 0x40, 0x2b, 0x8c, 0xcc, 0x55, 0x12, 0x0d, 0x92, 0x4a, 0xec, 0x62, 0xd7, 0x01, 0x05, 0x86,
	0x01, 0xc3, 0x30, 0x0c, 0x3b, 0xee, 0xcf, 0xe9, 0xb1, 0xc7, 0x61, 0x07, 0x63, 0x48, 0xfe, 0x03,
	0xff, 0x05, 0x85, 0x1e, 0x2d, 0x4b, 0x8e, 0xdd, 0x02, 0x42, 0x4f, 0xb6, 0xde, 0xf7, 0xf8, 0x7d,
	0xdf, 0x7b, 0x7c, 0x12, 0x89, 0xaa, 0x94, 0x8d, 0xfa, 0xb1, 0x8c, 0xba, 0x43, 0x2a, 0x69, 0xa8,
	0x3a, 0x43, 0x29, 0xb4, 0xa8, 0x34, 0x15, 0xe3, 0xf0, 0xcf, 0x13, 0x41, 0x47, 0x31, 0xee, 0x0d,
	0x28, 0x8f, 0x3a, 0xb3, 0xd4, 0xfd, 0xaa, 0x2f, 0x7c, 0x01, 0x70, 0x37, 0xf9, 0x67, 0xd6, 0xe0,
	0x97, 0xbb, 0x68, 0xfd, 0x04, 0x48, 0x2a, 0x87, 0xe8, 0x4e, 0x92, 0xe8, 0xb2, 0x88, 0xf6, 0x03,
	0x76, 0x6e, 0x5b, 0x6d, 0xeb, 0xe0, 0xe3, 0x5e, 0x63, 0x3a, 0x71, 0x76, 0xc7, 0x34, 0x0c, 0x0e,
	0x71, 0x1e, 0xc5, 0x64, 0x23, 0x79, 0xfc, 0xca, 0x3c, 0x55, 0x7e, 0x42, 0xe5, 0x90, 0x47, 0x2e,
	0x64, 0x48, 0xaa, 0x99, 0xfd, 0x41, 0xdb, 0x3a, 0xf8, 0xa4, 0xf7, 0xf8, 0xd5, 0xc4, 0x29, 0xfd,
	0x37, 0x71, 0xee, 0xfb, 0x5c, 0x0f, 0xe2, 0x7e, 0xc7, 0x13, 0x61, 0xd7, 0x13, 0x2a, 0x14, 0x6a,
	0xf6, 0xf3, 0x40, 0x9d, 0x3f, 0xef, 0xea, 0xf1, 0x90, 0xa9, 0xce, 0x97, 0xcc, 0x9b, 0x4e, 0x9c,
	0xaa, 0x91, 0x5a, 0x20, 0xc3, 0x64, 0x23, 0xe4, 0x51, 0x2f, 0x96, 0x11, 0xa1, 0x9a, 0x81, 0x16,
	0x1d, 0xe5, 0xb4, 0x3e, 0x7c, 0x4f, 0xad, 0x3c, 0x59, 0xa2, 0x45, 0x47, 0x73, 0x2d, 0x85, 0xb6,
	0x35, 0x95, 0x3e, 0xd3, 0x39, 0xb9, 0x35, 0x90, 0x3b, 0x2e, 0x2c, 0xd7, 0x30, 0x72, 0xb7, 0xf9,
	0x30, 0xd9, 0x34, 0xa1, 0xb9, 0xe8, 0x25, 0xda, 0x09, 0xc4, 0x95, 0xeb, 0x53, 0xe5, 0xea, 0x81,
	0x64, 0x6a, 0x20, 0x82, 0x73, 0xfb, 0x23, 0x50, 0xfd, 0xa6, 0xb0, 0xaa, 0x6d, 0x54, 0x97, 0x08,
	0x31, 0xd9, 0x0a, 0xc4, 0xd5, 0x11, 0x55, 0x67, 0x69, 0xa4, 0x32, 0x46, 0x95, 0x01, 0xf7, 0x07,
	0xb7, 0x84, 0xd7, 0x41, 0xf8, 0x49, 0x61, 0xe1, 0x3d, 0x23, 0xbc, 0xcc, 0x88, 0xc9, 0x76, 0x12,
	0x5c, 0x90, 0x3e, 0x46, 0x3b, 0x3c, 0xba, 0x08, 0xa8, 0xe6, 0x22, 0x1b, 0x40, 0x04, 0x03, 0xd8,
	0xcc, 0x8a, 0x58, 0x4a, 0xc1, 0x64, 0x7b, 0x1e, 0x4b, 0x47, 0xf1, 0x37, 0x0b, 0xed, 0x25, 0x5b,
	0x4a, 0xa3, 0x28, 0xa6, 0x81, 0x9b, 0xad, 0x81, 0xcd, 0xdb, 0x80, 0x6a, 0x48, 0xe1, 0x6a, 0xda,
	0xd9, 0xac, 0xac, 0x24, 0xc6, 0xa4, 0x1e, 0xd2, 0xd1, 0x43, 0x80, 0x8e, 0x53, 0x04, 0x76, 0xf3,
	0x4f, 0x0b, 0x35, 0x93, 0x65, 0x11, 0xd3, 0xae, 0x8a, 0x87, 0xc3, 0x60, 0x0c, 0x0b, 0xdc, 0x21,
	0x93, 0xee, 0x98, 0x51, 0x69, 0xdf, 0x01, 0x4b, 0x4f, 0x0b, 0x5b, 0xba, 0x97, 0x59, 0x7a, 0x1b,
	0x37, 0x26, 0x8d, 0x90, 0x8e, 0xbe, 0x63, 0xfa, 0x14, 0xc0, 0xc4, 0xcf, 0x09, 0x93, 0x3f, 0x32,
	0x2a, 0x2b, 0x11, 0xda, 0xe4, 0x11, 0xd7, 0x9c, 0x06, 0xb3, 0x95, 0x76, 0x19, 0x7c, 0x1c, 0x15,
	0xf0, 0x71, 0x1c, 0xe9, 0xe9, 0xc4, 0xa9, 0xa5, 0x9b, 0x93, 0x67, 0xc3, 0xa4, 0x3c, 0x0b, 0x18,
	0xe9, 0xca, 0x1f, 0x16, 0xba, 0x9b, 0xbc, 0xd5, 0xc9, 0x28, 0xc4, 0x8a, 0xfa, 0xcc, 0xbd, 0x10,
	0x32, 0x6b, 0xa2, 0xbd, 0x09, 0xea, 0x67, 0x85, 0xbb, 0x80, 0xb3, 0x0f, 0xc6, 0x5b, 0xa8, 0x93,
	0x26, 0xf0, 0xe8, 0x88, 0xaa, 0xa7, 0x09, 0xf6, 0x58, 0xc8, 0xf9, 0xfe, 0x54, 0x7a, 0x68, 0x8b,
	0x0d, 0x85, 0x37, 0x50, 0xd9, 0x6e, 0x6c, 0xb5, 0xad, 0x83, 0xb5, 0xde, 0xfe, 0x74, 0xe2, 0xd4,
	0x0d, 0xf3, 0xad, 0x04, 0x4c, 0xca, 0x26, 0x92, 0x36, 0xf2, 0x0c, 0xd5, 0x24, 0xbb, 0x64, 0x52,
	0x31, 0xb7, 0x2f, 0xe9, 0x73, 0x36, 0x1f, 0xdf, 0x2a, 0x8c, 0x6f, 0x7b, 0x3a, 0x71, 0x9a, 0x86,
	0x69, 0x65, 0x1a, 0x26, 0xbb, 0xb3, 0x78, 0x2f, 0x09, 0xa7, 0x53, 0xcc, 0xd0, 0xdd, 0xc5, 0x74,
	0x2d, 0xb9, 0xef, 0x33, 0xe9, 0x7a, 0x22, 0x8e, 0xb4, 0x5d, 0x6b, 0x5b, 0x07, 0xe5, 0xde, 0xfd,
	0xac, 0xfe, 0x77, 0x24, 0x63, 0x62, 0xe7, 0x15, 0xce, 0x0c, 0xf6, 0x28, 0x81, 0x2a, 0x7f, 0x59,
	0xa8, 0xb9, 0xb8, 0x54, 0xb2, 0xf3, 0xd8, 0xcb, 0xde, 0x97, 0xfa, 0xfb, 0x0d, 0xe7, 0xbb, 0xb8,
	0x31, 0xd9, 0xcb, 0xfb, 0x22, 0x29, 0x08, 0x6f, 0xcd, 0x33, 0xd4, 0xe0, 0x91, 0x27, 0x42, 0xe6,
	0xaa, 0x50, 0x08, 0x3d, 0x60, 0x72, 0xde, 0xd7, 0x16, 0xf4, 0x15, 0x4f, 0x27, 0x4e, 0x2b, 0x9d,
	0xbc, 0x95, 0x89, 0x98, 0xd4, 0x0c, 0x72, 0x3a, 0x03, 0xd2, 0xde, 0xfe, 0x6a, 0x21, 0xbb, 0x1f,
	0x5f, 0x5c, 0x40, 0x83, 0x22, 0x2d, 0x79, 0x3f, 0xce, 0x0a, 0x76, 0xa0, 0xe0, 0x1f, 0x0a, 0x17,
	0xec, 0xa4, 0x67, 0xe4, 0x6a, 0x5e, 0x4c, 0xea, 0x06, 0x7a, 0x94, 0x43, 0xa0, 0xd2, 0x9f, 0xd1,
	0xee, 0x6c, 0x91, 0x64, 0x01, 0xa3, 0x8a, 0x19, 0x1f, 0x6d, 0xf0, 0xf1, 0x6d, 0x61, 0x1f, 0xfb,
	0x0b, 0x3e, 0xf2, 0x94, 0x98, 0xec, 0x98, 0x28, 0x31, 0x41, 0x50, 0x7f, 0x69, 0xa1, 0x06, 0x7c,
	0xa2, 0xa9, 0xa7, 0xf9, 0x25, 0xd7, 0xe3, 0xdc, 0x97, 0xff, 0x33, 0xb0, 0x70, 0x52, 0xd8, 0x42,
	0x2b, 0xf7, 0xe5, 0x5f, 0xa6, 0xc5, 0xa4, 0x96, 0x20, 0x0f, 0x67, 0x40, 0x76, 0x06, 0xfc, 0x62,
	0xa1, 0x7a, 0x72, 0x4c, 0xad, 0x70, 0x82, 0xc1, 0xc9, 0xf7, 0x85, 0x9d, 0x7c, 0x9a, 0x1d, 0x7e,
	0xab, 0x8c, 0x54, 0x03, 0x71, 0xb5, 0xec, 0x63, 0x88, 0xb6, 0xcc, 0x95, 0x00, 0x3a, 0xa8, 0xf8,
	0x0b, 0x66, 0xdf, 0x03, 0xfd, 0xaf, 0x0b, 0xeb, 0xd7, 0xf3, 0x37, 0x8c, 0x39, 0x1d, 0x26, 0x65,
	0xb8, 0x63, 0x24, 0x81, 0x53, 0xfe, 0x82, 0x1d, 0xae, 0xfd, 0xfd, 0x8f, 0x53, 0xea, 0x3d, 0x79,
	0x75, 0xdd, 0xb2, 0x5e, 0x5f, 0xb7, 0xac, 0xff, 0xaf, 0x5b, 0xd6, 0xef, 0x37, 0xad, 0xd2, 0xeb,
	0x9b, 0x56, 0xe9, 0xdf, 0x9b, 0x56, 0xe9, 0xd9, 0xe7, 0x39, 0x41, 0xc5, 0xf8, 0x83, 0xf4, 0x92,
	0x07, 0x0f, 0x70, 0xcb, 0xeb, 0x8e, 0xba, 0xe9, 0x95, 0x10, 0xf4, 0xfb, 0xeb, 0x90, 0xf3, 0xc5,
	0x9b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x14, 0xa7, 0xa2, 0x2a, 0x0a, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxBufferSize.Size()
		i -= size
		if _, err := m.MaxBufferSize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x9a
	{
		size := m.LowActivityThreshold.Size()
		i -= size
		if _, err := m.LowActivityThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x92
	{
		size := m.HighActivityThreshold.Size()
		i -= size
		if _, err := m.HighActivityThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x8a
	{
		size := m.BufferReleaseRate.Size()
		i -= size
		if _, err := m.BufferReleaseRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x82
	{
		size := m.BufferContributionRate.Size()
		i -= size
		if _, err := m.BufferContributionRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xfa
	if m.IncomeSmootherEnabled {
		i--
		if m.IncomeSmootherEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	{
		size := m.ReverseBrakeReductionRate.Size()
		i -= size
		if _, err := m.ReverseBrakeReductionRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xb2
	if m.ReverseBrakeTriggerCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ReverseBrakeTriggerCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.ReverseBrakeEnabled {
		i--
		if m.ReverseBrakeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.EpochsPerYear != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochsPerYear))
		i--
		dAtA[i] = 0x78
	}
	{
		size := m.MinGasUsageForInflation.Size()
		i -= size
		if _, err := m.MinGasUsageForInflation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size := m.InitialSupply.Size()
		i -= size
		if _, err := m.InitialSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size := m.MaxNetSupplyRatePerYear.Size()
		i -= size
		if _, err := m.MaxNetSupplyRatePerYear.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size := m.MaxAnnualInflationRate.Size()
		i -= size
		if _, err := m.MaxAnnualInflationRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.InflationEnabled {
		i--
		if m.InflationEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	{
		size := m.HighGasThreshold.Size()
		i -= size
		if _, err := m.HighGasThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.LowGasThreshold.Size()
		i -= size
		if _, err := m.LowGasThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.TargetBurnRate.Size()
		i -= size
		if _, err := m.TargetBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MaxBurnRate.Size()
		i -= size
		if _, err := m.MaxBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinBurnRate.Size()
		i -= size
		if _, err := m.MinBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.BurnEnabled {
		i--
		if m.BurnEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BurnEnabled {
		n += 2
	}
	l = m.MinBurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxBurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TargetBurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.LowGasThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.HighGasThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.InflationEnabled {
		n += 2
	}
	l = m.MaxAnnualInflationRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxNetSupplyRatePerYear.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.InitialSupply.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinGasUsageForInflation.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.EpochsPerYear != 0 {
		n += 1 + sovParams(uint64(m.EpochsPerYear))
	}
	if m.ReverseBrakeEnabled {
		n += 3
	}
	if m.ReverseBrakeTriggerCount != 0 {
		n += 2 + sovParams(uint64(m.ReverseBrakeTriggerCount))
	}
	l = m.ReverseBrakeReductionRate.Size()
	n += 2 + l + sovParams(uint64(l))
	if m.IncomeSmootherEnabled {
		n += 3
	}
	l = m.BufferContributionRate.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.BufferReleaseRate.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.HighActivityThreshold.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.LowActivityThreshold.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.MaxBufferSize.Size()
	n += 2 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BurnEnabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowGasThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LowGasThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighGasThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HighGasThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InflationEnabled = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAnnualInflationRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxAnnualInflationRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNetSupplyRatePerYear", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxNetSupplyRatePerYear.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasUsageForInflation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinGasUsageForInflation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochsPerYear", wireType)
			}
			m.EpochsPerYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochsPerYear |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReverseBrakeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReverseBrakeEnabled = bool(v != 0)
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReverseBrakeTriggerCount", wireType)
			}
			m.ReverseBrakeTriggerCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReverseBrakeTriggerCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReverseBrakeReductionRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReverseBrakeReductionRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncomeSmootherEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IncomeSmootherEnabled = bool(v != 0)
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferContributionRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferContributionRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferReleaseRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferReleaseRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 33:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighActivityThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HighActivityThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 34:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowActivityThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LowActivityThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 35:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBufferSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBufferSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
