// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aexburn/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryBurnStatsRequest is the request type for the Query/BurnStats RPC method.
type QueryBurnStatsRequest struct {
}

func (m *QueryBurnStatsRequest) Reset()         { *m = QueryBurnStatsRequest{} }
func (m *QueryBurnStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBurnStatsRequest) ProtoMessage()    {}
func (*QueryBurnStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{2}
}
func (m *QueryBurnStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBurnStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBurnStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBurnStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBurnStatsRequest.Merge(m, src)
}
func (m *QueryBurnStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBurnStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBurnStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBurnStatsRequest proto.InternalMessageInfo

// QueryBurnStatsResponse is the response type for the Query/BurnStats RPC method.
type QueryBurnStatsResponse struct {
	BurnStats BurnStats `protobuf:"bytes,1,opt,name=burn_stats,json=burnStats,proto3" json:"burn_stats"`
}

func (m *QueryBurnStatsResponse) Reset()         { *m = QueryBurnStatsResponse{} }
func (m *QueryBurnStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBurnStatsResponse) ProtoMessage()    {}
func (*QueryBurnStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{3}
}
func (m *QueryBurnStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBurnStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBurnStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBurnStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBurnStatsResponse.Merge(m, src)
}
func (m *QueryBurnStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBurnStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBurnStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBurnStatsResponse proto.InternalMessageInfo

func (m *QueryBurnStatsResponse) GetBurnStats() BurnStats {
	if m != nil {
		return m.BurnStats
	}
	return BurnStats{}
}

// QueryInflationStatsRequest is the request type for the Query/InflationStats RPC method.
type QueryInflationStatsRequest struct {
}

func (m *QueryInflationStatsRequest) Reset()         { *m = QueryInflationStatsRequest{} }
func (m *QueryInflationStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInflationStatsRequest) ProtoMessage()    {}
func (*QueryInflationStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{4}
}
func (m *QueryInflationStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationStatsRequest.Merge(m, src)
}
func (m *QueryInflationStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationStatsRequest proto.InternalMessageInfo

// QueryInflationStatsResponse is the response type for the Query/InflationStats RPC method.
type QueryInflationStatsResponse struct {
	InflationStats InflationStats `protobuf:"bytes,1,opt,name=inflation_stats,json=inflationStats,proto3" json:"inflation_stats"`
}

func (m *QueryInflationStatsResponse) Reset()         { *m = QueryInflationStatsResponse{} }
func (m *QueryInflationStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInflationStatsResponse) ProtoMessage()    {}
func (*QueryInflationStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{5}
}
func (m *QueryInflationStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationStatsResponse.Merge(m, src)
}
func (m *QueryInflationStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationStatsResponse proto.InternalMessageInfo

func (m *QueryInflationStatsResponse) GetInflationStats() InflationStats {
	if m != nil {
		return m.InflationStats
	}
	return InflationStats{}
}

// QueryMonthlyBurnDataRequest is the request type for the Query/MonthlyBurnData RPC method.
type QueryMonthlyBurnDataRequest struct {
}

func (m *QueryMonthlyBurnDataRequest) Reset()         { *m = QueryMonthlyBurnDataRequest{} }
func (m *QueryMonthlyBurnDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMonthlyBurnDataRequest) ProtoMessage()    {}
func (*QueryMonthlyBurnDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{6}
}
func (m *QueryMonthlyBurnDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMonthlyBurnDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMonthlyBurnDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMonthlyBurnDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMonthlyBurnDataRequest.Merge(m, src)
}
func (m *QueryMonthlyBurnDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMonthlyBurnDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMonthlyBurnDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMonthlyBurnDataRequest proto.InternalMessageInfo

// QueryMonthlyBurnDataResponse is the response type for the Query/MonthlyBurnData RPC method.
type QueryMonthlyBurnDataResponse struct {
	MonthlyBurnData []MonthlyBurnData `protobuf:"bytes,1,rep,name=monthly_burn_data,json=monthlyBurnData,proto3" json:"monthly_burn_data"`
}

func (m *QueryMonthlyBurnDataResponse) Reset()         { *m = QueryMonthlyBurnDataResponse{} }
func (m *QueryMonthlyBurnDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMonthlyBurnDataResponse) ProtoMessage()    {}
func (*QueryMonthlyBurnDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{7}
}
func (m *QueryMonthlyBurnDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMonthlyBurnDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMonthlyBurnDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMonthlyBurnDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMonthlyBurnDataResponse.Merge(m, src)
}
func (m *QueryMonthlyBurnDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMonthlyBurnDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMonthlyBurnDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMonthlyBurnDataResponse proto.InternalMessageInfo

func (m *QueryMonthlyBurnDataResponse) GetMonthlyBurnData() []MonthlyBurnData {
	if m != nil {
		return m.MonthlyBurnData
	}
	return nil
}

// QueryNetSupplyRequest is the request type for the Query/NetSupply RPC method.
type QueryNetSupplyRequest struct {
}

func (m *QueryNetSupplyRequest) Reset()         { *m = QueryNetSupplyRequest{} }
func (m *QueryNetSupplyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNetSupplyRequest) ProtoMessage()    {}
func (*QueryNetSupplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{8}
}
func (m *QueryNetSupplyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNetSupplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNetSupplyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNetSupplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNetSupplyRequest.Merge(m, src)
}
func (m *QueryNetSupplyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNetSupplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNetSupplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNetSupplyRequest proto.InternalMessageInfo

// QueryNetSupplyResponse is the response type for the Query/NetSupply RPC method.
type QueryNetSupplyResponse struct {
	// total_minted_12m is the total minted in the 12-month window
	TotalMinted_12M github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=total_minted_12m,json=totalMinted12m,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_minted_12m"`
	// total_burned_12m is the total burned in the 12-month window
	TotalBurned_12M github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=total_burned_12m,json=totalBurned12m,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_burned_12m"`
	// net_supply_change is the net supply change (minted - burned)
	NetSupplyChange github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=net_supply_change,json=netSupplyChange,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"net_supply_change"`
	// net_supply_rate is the net supply change as a percentage of initial supply
	NetSupplyRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=net_supply_rate,json=netSupplyRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"net_supply_rate"`
	// max_allowed_net_supply is the maximum allowed net supply (5% of initial)
	MaxAllowedNetSupply github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=max_allowed_net_supply,json=maxAllowedNetSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"max_allowed_net_supply"`
	// remaining_mint_capacity is how much more can be minted within constraints
	RemainingMintCapacity github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=remaining_mint_capacity,json=remainingMintCapacity,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"remaining_mint_capacity"`
}

func (m *QueryNetSupplyResponse) Reset()         { *m = QueryNetSupplyResponse{} }
func (m *QueryNetSupplyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNetSupplyResponse) ProtoMessage()    {}
func (*QueryNetSupplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{9}
}
func (m *QueryNetSupplyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNetSupplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNetSupplyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNetSupplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNetSupplyResponse.Merge(m, src)
}
func (m *QueryNetSupplyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNetSupplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNetSupplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNetSupplyResponse proto.InternalMessageInfo

// QueryEpochGasDataRequest is the request type for the Query/EpochGasData RPC method.
type QueryEpochGasDataRequest struct {
}

func (m *QueryEpochGasDataRequest) Reset()         { *m = QueryEpochGasDataRequest{} }
func (m *QueryEpochGasDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochGasDataRequest) ProtoMessage()    {}
func (*QueryEpochGasDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{10}
}
func (m *QueryEpochGasDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochGasDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochGasDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochGasDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochGasDataRequest.Merge(m, src)
}
func (m *QueryEpochGasDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochGasDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochGasDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochGasDataRequest proto.InternalMessageInfo

// QueryEpochGasDataResponse is the response type for the Query/EpochGasData RPC method.
type QueryEpochGasDataResponse struct {
	// total_gas_used is the cumulative gas used in the current epoch
	TotalGasUsed github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=total_gas_used,json=totalGasUsed,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_gas_used"`
	// total_gas_limit is the cumulative gas limit in the current epoch
	TotalGasLimit github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=total_gas_limit,json=totalGasLimit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_gas_limit"`
	// block_count is the number of blocks in the current epoch
	BlockCount uint64 `protobuf:"varint,3,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	// usage_rate is the calculated gas usage rate (total_gas_used / total_gas_limit)
	UsageRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=usage_rate,json=usageRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"usage_rate"`
}

func (m *QueryEpochGasDataResponse) Reset()         { *m = QueryEpochGasDataResponse{} }
func (m *QueryEpochGasDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochGasDataResponse) ProtoMessage()    {}
func (*QueryEpochGasDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c657c48b078c0ed, []int{11}
}
func (m *QueryEpochGasDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochGasDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochGasDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochGasDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochGasDataResponse.Merge(m, src)
}
func (m *QueryEpochGasDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochGasDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochGasDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochGasDataResponse proto.InternalMessageInfo

func (m *QueryEpochGasDataResponse) GetBlockCount() uint64 {
	if m != nil {
		return m.BlockCount
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "seiprotocol.seichain.aexburn.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "seiprotocol.seichain.aexburn.QueryParamsResponse")
	proto.RegisterType((*QueryBurnStatsRequest)(nil), "seiprotocol.seichain.aexburn.QueryBurnStatsRequest")
	proto.RegisterType((*QueryBurnStatsResponse)(nil), "seiprotocol.seichain.aexburn.QueryBurnStatsResponse")
	proto.RegisterType((*QueryInflationStatsRequest)(nil), "seiprotocol.seichain.aexburn.QueryInflationStatsRequest")
	proto.RegisterType((*QueryInflationStatsResponse)(nil), "seiprotocol.seichain.aexburn.QueryInflationStatsResponse")
	proto.RegisterType((*QueryMonthlyBurnDataRequest)(nil), "seiprotocol.seichain.aexburn.QueryMonthlyBurnDataRequest")
	proto.RegisterType((*QueryMonthlyBurnDataResponse)(nil), "seiprotocol.seichain.aexburn.QueryMonthlyBurnDataResponse")
	proto.RegisterType((*QueryNetSupplyRequest)(nil), "seiprotocol.seichain.aexburn.QueryNetSupplyRequest")
	proto.RegisterType((*QueryNetSupplyResponse)(nil), "seiprotocol.seichain.aexburn.QueryNetSupplyResponse")
	proto.RegisterType((*QueryEpochGasDataRequest)(nil), "seiprotocol.seichain.aexburn.QueryEpochGasDataRequest")
	proto.RegisterType((*QueryEpochGasDataResponse)(nil), "seiprotocol.seichain.aexburn.QueryEpochGasDataResponse")
}

func init() { proto.RegisterFile("aexburn/query.proto", fileDescriptor_8c657c48b078c0ed) }

var fileDescriptor_8c657c48b078c0ed = []byte{
	// 885 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x4d, 0x6f, 0xf3, 0x44,
	0x10, 0xc7, 0xe3, 0x3e, 0x79, 0x82, 0xb2, 0x7d, 0x09, 0xdd, 0xbe, 0xa5, 0x6e, 0x9a, 0x14, 0x53,
	0xd1, 0x0a, 0x51, 0x9b, 0xa4, 0x88, 0xb7, 0x1b, 0x69, 0x51, 0x55, 0xd1, 0x22, 0x48, 0x01, 0x41,
	0x39, 0x58, 0x1b, 0x67, 0xeb, 0x58, 0xb5, 0x77, 0xdd, 0xec, 0x1a, 0x12, 0x2e, 0x48, 0x7c, 0x00,
	0x84, 0xc4, 0x91, 0x2f, 0xc0, 0x8d, 0x0b, 0x17, 0xbe, 0x41, 0x2f, 0x48, 0x95, 0xb8, 0x20, 0x0e,
	0x15, 0x6a, 0x39, 0xf0, 0x31, 0x1e, 0x79, 0xbd, 0x76, 0x5e, 0x15, 0x25, 0xe9, 0x25, 0x71, 0x66,
	0x76, 0xfe, 0xf3, 0xf3, 0xce, 0x64, 0x06, 0xac, 0x20, 0xdc, 0xae, 0x07, 0x2d, 0x62, 0xdc, 0x04,
	0xb8, 0xd5, 0xd1, 0xfd, 0x16, 0xe5, 0x14, 0x16, 0x18, 0x76, 0xc4, 0x93, 0x45, 0x5d, 0x9d, 0x61,
	0xc7, 0x6a, 0x22, 0x87, 0xe8, 0xf2, 0xa4, 0xba, 0x6a, 0x53, 0x9b, 0x0a, 0xb7, 0x11, 0x3e, 0x45,
	0x31, 0x6a, 0xc1, 0xa6, 0xd4, 0x76, 0xb1, 0x81, 0x7c, 0xc7, 0x40, 0x84, 0x50, 0x8e, 0xb8, 0x43,
	0x09, 0x93, 0xde, 0xd5, 0x38, 0x8d, 0x8f, 0x5a, 0xc8, 0x8b, 0xad, 0x30, 0xb6, 0x86, 0x1f, 0x91,
	0x4d, 0x5b, 0x05, 0xf0, 0xd3, 0x10, 0xe5, 0x13, 0x71, 0xb0, 0x86, 0x6f, 0x02, 0xcc, 0xb8, 0xf6,
	0x15, 0x58, 0xe9, 0xb3, 0x32, 0x9f, 0x12, 0x86, 0x61, 0x15, 0x64, 0x22, 0xc1, 0xbc, 0xb2, 0xa3,
	0xec, 0xcf, 0x57, 0x76, 0xf5, 0x71, 0xe4, 0x7a, 0x14, 0x5d, 0x4d, 0xdf, 0xde, 0x97, 0x52, 0x35,
	0x19, 0xa9, 0x6d, 0x80, 0x35, 0x21, 0x5d, 0x0d, 0x5a, 0xe4, 0x82, 0x23, 0x9e, 0xe4, 0xbc, 0x02,
	0xeb, 0x83, 0x0e, 0x99, 0xf6, 0x0c, 0x80, 0x50, 0xcf, 0x64, 0xa1, 0x55, 0xa6, 0xde, 0x1b, 0x9f,
	0x3a, 0x11, 0x91, 0xd9, 0xb3, 0xf5, 0xd8, 0xa0, 0x15, 0x80, 0x2a, 0xf2, 0x9c, 0x92, 0x2b, 0x57,
	0x5c, 0x5a, 0x1f, 0xc5, 0x77, 0x60, 0x6b, 0xa4, 0x57, 0xa2, 0x7c, 0x0d, 0x72, 0x4e, 0xec, 0xe9,
	0xe3, 0x79, 0x63, 0x3c, 0x4f, 0xbf, 0x9c, 0x84, 0x5a, 0x72, 0xfa, 0xac, 0xda, 0xb6, 0xcc, 0x7d,
	0x4e, 0x09, 0x6f, 0xba, 0xe2, 0x22, 0x8e, 0x11, 0x47, 0x31, 0xda, 0xf7, 0xa0, 0x30, 0xda, 0x2d,
	0xd9, 0x4c, 0xb0, 0xec, 0x45, 0x2e, 0x53, 0x5c, 0x57, 0x03, 0x71, 0x94, 0x57, 0x76, 0x9e, 0xed,
	0xcf, 0x57, 0x0e, 0xc6, 0xd3, 0x0d, 0x28, 0x4a, 0xbc, 0x9c, 0xd7, 0x6f, 0x4e, 0x4a, 0xf7, 0x31,
	0xe6, 0x17, 0x81, 0xef, 0xbb, 0x9d, 0x98, 0xec, 0xcf, 0xb4, 0xac, 0x5d, 0x8f, 0x47, 0x42, 0x7d,
	0x09, 0x5e, 0xe6, 0x94, 0x23, 0xd7, 0xf4, 0x1c, 0xc2, 0x71, 0xc3, 0x2c, 0x57, 0x3c, 0x71, 0x63,
	0xd9, 0xaa, 0x1e, 0x26, 0xf9, 0xe7, 0xbe, 0xf4, 0x9a, 0xed, 0xf0, 0x66, 0x50, 0xd7, 0x2d, 0xea,
	0x19, 0x16, 0x65, 0x1e, 0x65, 0xf2, 0xeb, 0x80, 0x35, 0xae, 0x0d, 0xde, 0xf1, 0x31, 0xd3, 0x4f,
	0x09, 0xaf, 0x2d, 0x09, 0x9d, 0x73, 0x21, 0x53, 0xae, 0x78, 0x5d, 0xe5, 0xf0, 0x15, 0xa4, 0xf2,
	0xdc, 0x13, 0x94, 0xab, 0x42, 0x26, 0x54, 0xbe, 0x04, 0xcb, 0x04, 0x73, 0x93, 0x89, 0x37, 0x31,
	0xad, 0x26, 0x22, 0x36, 0xce, 0x3f, 0x9b, 0x49, 0x3a, 0x47, 0xe2, 0x1b, 0x39, 0x12, 0x32, 0xf0,
	0x0b, 0x90, 0xeb, 0xd1, 0x6e, 0x21, 0x8e, 0xf3, 0xe9, 0xa9, 0x95, 0x8f, 0xb1, 0x55, 0x5b, 0x4c,
	0x94, 0x6b, 0x88, 0x63, 0x68, 0x81, 0x75, 0x0f, 0xb5, 0x4d, 0xe4, 0xba, 0xf4, 0x5b, 0xdc, 0x30,
	0xbb, 0x39, 0xf2, 0xcf, 0x67, 0x02, 0x5f, 0xf1, 0x50, 0xfb, 0x83, 0x48, 0x2c, 0x29, 0x2a, 0xbc,
	0x02, 0x1b, 0x2d, 0xec, 0x21, 0x87, 0x38, 0xc4, 0x16, 0x05, 0x35, 0x2d, 0xe4, 0x23, 0xcb, 0xe1,
	0x9d, 0x7c, 0x66, 0xa6, 0x2c, 0x6b, 0x89, 0x5c, 0x58, 0xd7, 0x23, 0x29, 0xa6, 0xa9, 0x20, 0x2f,
	0xda, 0xe9, 0x43, 0x9f, 0x5a, 0xcd, 0x13, 0xc4, 0x7a, 0xff, 0x05, 0x7f, 0xcc, 0x81, 0xcd, 0x11,
	0x4e, 0xd9, 0x6e, 0x9f, 0x81, 0xa8, 0x98, 0xa6, 0x8d, 0x98, 0x19, 0x30, 0xdc, 0x98, 0xb1, 0xd9,
	0x16, 0x84, 0xca, 0x09, 0x62, 0x9f, 0x33, 0xdc, 0x08, 0x8b, 0xd6, 0x55, 0x75, 0x1d, 0xcf, 0xe1,
	0x33, 0x76, 0xda, 0x62, 0x2c, 0x7b, 0x16, 0x8a, 0xc0, 0x12, 0x98, 0xaf, 0xbb, 0xd4, 0xba, 0x36,
	0x2d, 0x1a, 0x10, 0x2e, 0x5a, 0x2c, 0x5d, 0x03, 0xc2, 0x74, 0x14, 0x5a, 0xe0, 0x39, 0x00, 0x01,
	0x43, 0x36, 0x7e, 0x4a, 0xa3, 0x64, 0x85, 0x42, 0xd8, 0x24, 0x95, 0xff, 0x5f, 0x02, 0xcf, 0xc5,
	0xdd, 0xc1, 0x1f, 0x15, 0x90, 0x89, 0xc6, 0x33, 0x7c, 0x73, 0xfc, 0x6c, 0x18, 0xde, 0x0e, 0x6a,
	0x79, 0x8a, 0x88, 0xa8, 0x2e, 0x5a, 0xe9, 0x87, 0xbf, 0xfe, 0xfb, 0x79, 0x6e, 0x13, 0x6e, 0x18,
	0x08, 0x33, 0xcb, 0x88, 0x17, 0xd1, 0x37, 0x65, 0xb9, 0xa1, 0xe0, 0x2f, 0x0a, 0xc8, 0x26, 0x43,
	0x1b, 0x1e, 0x4e, 0x90, 0x61, 0x70, 0x81, 0xa8, 0x6f, 0x4d, 0x17, 0x24, 0xc9, 0x5e, 0x15, 0x64,
	0xdb, 0x70, 0x6b, 0x88, 0xac, 0xbb, 0x73, 0xe0, 0x6f, 0x0a, 0x58, 0xea, 0x1f, 0xe1, 0xf0, 0xdd,
	0x09, 0xb2, 0x8d, 0x5c, 0x31, 0xea, 0x7b, 0x33, 0x44, 0x4a, 0xd8, 0x7d, 0x01, 0xab, 0xc1, 0x9d,
	0x21, 0xd8, 0x81, 0xad, 0x04, 0x7f, 0x57, 0x40, 0x6e, 0x60, 0xac, 0xc3, 0x49, 0x12, 0x8f, 0xde,
	0x3d, 0xea, 0xfb, 0xb3, 0x84, 0x4a, 0xe8, 0xd7, 0x05, 0xf4, 0x2e, 0xd4, 0x86, 0xa0, 0x87, 0xd6,
	0x95, 0x68, 0x83, 0xee, 0xbc, 0x99, 0xa4, 0x0d, 0x06, 0x97, 0xd1, 0x44, 0x6d, 0x30, 0xb4, 0xa7,
	0xc6, 0xb4, 0x41, 0x77, 0x94, 0xc2, 0x5f, 0x15, 0xb0, 0xd0, 0x3b, 0x76, 0xe0, 0xdb, 0x13, 0xe4,
	0x1a, 0x31, 0xc4, 0xd4, 0x77, 0xa6, 0x8e, 0x93, 0x98, 0x7b, 0x02, 0xf3, 0x15, 0x58, 0x1a, 0xc2,
	0xc4, 0xe1, 0x71, 0x31, 0xa0, 0xc2, 0x8b, 0xac, 0x7e, 0x74, 0xfb, 0x50, 0x54, 0xee, 0x1e, 0x8a,
	0xca, 0xbf, 0x0f, 0x45, 0xe5, 0xa7, 0xc7, 0x62, 0xea, 0xee, 0xb1, 0x98, 0xfa, 0xfb, 0xb1, 0x98,
	0xba, 0x2c, 0xf7, 0xcc, 0x0d, 0x86, 0x9d, 0x83, 0x18, 0x43, 0xfc, 0x10, 0x1c, 0x46, 0x3b, 0x11,
	0x16, 0x63, 0xa4, 0x9e, 0x11, 0x67, 0x0e, 0x5f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x91, 0xf9, 0x9e,
	0xdf, 0xbe, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// BurnStats returns the cumulative burn statistics
	BurnStats(ctx context.Context, in *QueryBurnStatsRequest, opts ...grpc.CallOption) (*QueryBurnStatsResponse, error)
	// InflationStats returns the cumulative inflation statistics
	InflationStats(ctx context.Context, in *QueryInflationStatsRequest, opts ...grpc.CallOption) (*QueryInflationStatsResponse, error)
	// MonthlyBurnData returns the 12-month rolling window supply data
	MonthlyBurnData(ctx context.Context, in *QueryMonthlyBurnDataRequest, opts ...grpc.CallOption) (*QueryMonthlyBurnDataResponse, error)
	// NetSupply returns the current net supply change in the 12-month window
	NetSupply(ctx context.Context, in *QueryNetSupplyRequest, opts ...grpc.CallOption) (*QueryNetSupplyResponse, error)
	// EpochGasData returns the current epoch's accumulated gas data
	EpochGasData(ctx context.Context, in *QueryEpochGasDataRequest, opts ...grpc.CallOption) (*QueryEpochGasDataResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.aexburn.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BurnStats(ctx context.Context, in *QueryBurnStatsRequest, opts ...grpc.CallOption) (*QueryBurnStatsResponse, error) {
	out := new(QueryBurnStatsResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.aexburn.Query/BurnStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InflationStats(ctx context.Context, in *QueryInflationStatsRequest, opts ...grpc.CallOption) (*QueryInflationStatsResponse, error) {
	out := new(QueryInflationStatsResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.aexburn.Query/InflationStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MonthlyBurnData(ctx context.Context, in *QueryMonthlyBurnDataRequest, opts ...grpc.CallOption) (*QueryMonthlyBurnDataResponse, error) {
	out := new(QueryMonthlyBurnDataResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.aexburn.Query/MonthlyBurnData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NetSupply(ctx context.Context, in *QueryNetSupplyRequest, opts ...grpc.CallOption) (*QueryNetSupplyResponse, error) {
	out := new(QueryNetSupplyResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.aexburn.Query/NetSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochGasData(ctx context.Context, in *QueryEpochGasDataRequest, opts ...grpc.CallOption) (*QueryEpochGasDataResponse, error) {
	out := new(QueryEpochGasDataResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.aexburn.Query/EpochGasData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the module parameters
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// BurnStats returns the cumulative burn statistics
	BurnStats(context.Context, *QueryBurnStatsRequest) (*QueryBurnStatsResponse, error)
	// InflationStats returns the cumulative inflation statistics
	InflationStats(context.Context, *QueryInflationStatsRequest) (*QueryInflationStatsResponse, error)
	// MonthlyBurnData returns the 12-month rolling window supply data
	MonthlyBurnData(context.Context, *QueryMonthlyBurnDataRequest) (*QueryMonthlyBurnDataResponse, error)
	// NetSupply returns the current net supply change in the 12-month window
	NetSupply(context.Context, *QueryNetSupplyRequest) (*QueryNetSupplyResponse, error)
	// EpochGasData returns the current epoch's accumulated gas data
	EpochGasData(context.Context, *QueryEpochGasDataRequest) (*QueryEpochGasDataResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) BurnStats(ctx context.Context, req *QueryBurnStatsRequest) (*QueryBurnStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnStats not implemented")
}
func (*UnimplementedQueryServer) InflationStats(ctx context.Context, req *QueryInflationStatsRequest) (*QueryInflationStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InflationStats not implemented")
}
func (*UnimplementedQueryServer) MonthlyBurnData(ctx context.Context, req *QueryMonthlyBurnDataRequest) (*QueryMonthlyBurnDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonthlyBurnData not implemented")
}
func (*UnimplementedQueryServer) NetSupply(ctx context.Context, req *QueryNetSupplyRequest) (*QueryNetSupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetSupply not implemented")
}
func (*UnimplementedQueryServer) EpochGasData(ctx context.Context, req *QueryEpochGasDataRequest) (*QueryEpochGasDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochGasData not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.aexburn.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BurnStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBurnStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BurnStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.aexburn.Query/BurnStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BurnStats(ctx, req.(*QueryBurnStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InflationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInflationStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InflationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.aexburn.Query/InflationStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InflationStats(ctx, req.(*QueryInflationStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MonthlyBurnData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMonthlyBurnDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MonthlyBurnData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.aexburn.Query/MonthlyBurnData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MonthlyBurnData(ctx, req.(*QueryMonthlyBurnDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NetSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNetSupplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NetSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.aexburn.Query/NetSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NetSupply(ctx, req.(*QueryNetSupplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochGasData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochGasDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochGasData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.aexburn.Query/EpochGasData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochGasData(ctx, req.(*QueryEpochGasDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.aexburn.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BurnStats",
			Handler:    _Query_BurnStats_Handler,
		},
		{
			MethodName: "InflationStats",
			Handler:    _Query_InflationStats_Handler,
		},
		{
			MethodName: "MonthlyBurnData",
			Handler:    _Query_MonthlyBurnData_Handler,
		},
		{
			MethodName: "NetSupply",
			Handler:    _Query_NetSupply_Handler,
		},
		{
			MethodName: "EpochGasData",
			Handler:    _Query_EpochGasData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aexburn/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBurnStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBurnStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBurnStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryBurnStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBurnStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBurnStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BurnStats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryInflationStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInflationStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.InflationStats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMonthlyBurnDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMonthlyBurnDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMonthlyBurnDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryMonthlyBurnDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMonthlyBurnDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMonthlyBurnDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MonthlyBurnData) > 0 {
		for iNdEx := len(m.MonthlyBurnData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MonthlyBurnData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryNetSupplyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNetSupplyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNetSupplyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryNetSupplyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNetSupplyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNetSupplyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RemainingMintCapacity.Size()
		i -= size
		if _, err := m.RemainingMintCapacity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MaxAllowedNetSupply.Size()
		i -= size
		if _, err := m.MaxAllowedNetSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.NetSupplyRate.Size()
		i -= size
		if _, err := m.NetSupplyRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.NetSupplyChange.Size()
		i -= size
		if _, err := m.NetSupplyChange.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TotalBurned_12M.Size()
		i -= size
		if _, err := m.TotalBurned_12M.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TotalMinted_12M.Size()
		i -= size
		if _, err := m.TotalMinted_12M.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEpochGasDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochGasDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochGasDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEpochGasDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochGasDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochGasDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.UsageRate.Size()
		i -= size
		if _, err := m.UsageRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.BlockCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockCount))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.TotalGasLimit.Size()
		i -= size
		if _, err := m.TotalGasLimit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TotalGasUsed.Size()
		i -= size
		if _, err := m.TotalGasUsed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBurnStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryBurnStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BurnStats.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryInflationStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInflationStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.InflationStats.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMonthlyBurnDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryMonthlyBurnDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MonthlyBurnData) > 0 {
		for _, e := range m.MonthlyBurnData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryNetSupplyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryNetSupplyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalMinted_12M.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.TotalBurned_12M.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.NetSupplyChange.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.NetSupplyRate.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.MaxAllowedNetSupply.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.RemainingMintCapacity.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEpochGasDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEpochGasDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalGasUsed.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.TotalGasLimit.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.BlockCount != 0 {
		n += 1 + sovQuery(uint64(m.BlockCount))
	}
	l = m.UsageRate.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBurnStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBurnStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBurnStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBurnStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBurnStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBurnStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMonthlyBurnDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMonthlyBurnDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMonthlyBurnDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMonthlyBurnDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMonthlyBurnDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMonthlyBurnDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthlyBurnData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MonthlyBurnData = append(m.MonthlyBurnData, MonthlyBurnData{})
			if err := m.MonthlyBurnData[len(m.MonthlyBurnData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNetSupplyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNetSupplyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNetSupplyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNetSupplyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNetSupplyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNetSupplyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMinted_12M", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalMinted_12M.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurned_12M", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalBurned_12M.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetSupplyChange", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetSupplyChange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetSupplyRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetSupplyRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAllowedNetSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxAllowedNetSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingMintCapacity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingMintCapacity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochGasDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochGasDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochGasDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochGasDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochGasDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochGasDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalGasUsed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalGasUsed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalGasLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalGasLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockCount", wireType)
			}
			m.BlockCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsageRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UsageRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
